[package]
name = "ch1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "ex1"
path = "examples/ex1.rs"

[[example]]
name = "sol1"
path = "examples/ex1_solution.rs"